### ISSUE TITLE
dev: linter/formatter

### ISSUE THREAD

**Issue by Blemming** [FloKaemmerer/dynamic-atlas#41]
Do you use a linter or a formatter to format your project ? I really like [Antfu's preset](https://github.com/antfu/eslint-config) combined with eslint vscode extension.

Maybe add a .vscode with extension [recommendations](https://code.visualstudio.com/docs/editor/extension-marketplace#_workspace-recommended-extensions)

**Comment by FloKaemmerer** [comment]
I'm using the default formatter/linter that is shipped with intellij ultimate. (Since I'm a java backend developer, I felt more at home in that ide then vscode).

Is there a preset for intellij that has the same result as the one for viscose? 
Feel free to at any preset you deem useful.

**Comment by FloKaemmerer** [comment]
The second option with antfu's preset sounds good to me.

The current configs came with the default vue3 setup which I used to start the project, so feel free to replace them.

I'll get the plugin for intellij than.

**Comment by Blemming** [comment]
#42 Should take care of it :)
